### ISSUE TITLE
loading an `AtmosphericPSF` from a pickle file no longer works

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#234] opened 2019-10-31 17:55 UTC
@jmeyers314 Using galsim v2.2.1, the mechanism we had for saving an `AtmosphericPSF` to a pickle file then reading it in for a later `imsim.py` run no longer works.   Here's a self-contained script that shows the problem:
```
import subprocess
import desc.imsim

commands = {'rightascension': 61.99398718973142,
 'declination': -32.83695608408115,
 'mjd': 60278.28041661111,
 'altitude': 58.81635120206924,
 'azimuth': 255.71142857124866,
 'filter': 3,
 'rotskypos': 265.809115420881,
 'camconfig': 1,
 'dist2moon': 74.5977298,
 'moonalt': 30.9167693,
 'moondec': 28.6386564,
 'moonphase': 90.8750305,
 'moonra': 104.4448764,
 'nsnap': 1,
 'obshistid': 479028,
 'rottelpos': 1.1543954,
 'seed': 479028,
 'seeing': 0.512611,
 'sunalt': -29.2091162,
 'vistime': 30,
 'minsource': 100,
 'bandpass': 'i'}
obs_md = desc.imsim.phosim_obs_metadata(commands)

psf = desc.imsim.make_psf('Atmospheric', obs_md, #log_level='DEBUG',
                          screen_scale=6.4)

psf_file = 'atm_psf.pkl'
desc.imsim.save_psf(psf, psf_file)

# This works:
desc.imsim.load_psf(psf_file)

# but loading in a new python session results in a KeyError:
subprocess.check_call(f'''python -c "import desc.imsim; desc.imsim.load_psf('{psf_file}')"''', shell=True)
```
Here's the output I get:
```
CameraMapper INFO: Loading Posix exposure registry from .
CameraMapper INFO: Loading Posix exposure registry from .
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/global/u1/j/jchiang8/dev/imSim/python/desc/imsim/imSim.py", line 873, in load_psf
    psf = pickle.load(fd)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.12-1172c30/Linux64/galsim/2.2.1.lsst/lib/python/galsim/phase_screens.py", line 298, in __setstate__
    self._objDict = _GSScreenShare[self._shareKey]
KeyError: 46914331211872
Traceback (most recent call last):
  File "make_atm_psf.py", line 38, in <module>
    subprocess.check_call(f'''python -c "import desc.imsim; desc.imsim.load_psf('{psf_file}')"''', shell=True)
  File "/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -c "import desc.imsim; desc.imsim.load_psf('atm_psf.pkl')"' returned non-zero exit status 1.
```
Could you have a look please?

**Comment by rmjarvis** [comment] 2019-11-01 01:08
@jmeyers314 I reproduced this is a purely GalSim context.  I pushed a test that currently fails to GalSim branch  `atm_pkl` if you want to take a look.

The problem is that the pickling stuff for atmospheres relies on a global dict.  This is appropriate for pickles that pass among processes in a single run.  But not for pickles that are written to disk and then read back in.

So I think we need two different serialization for these.  The current one will be used whenever python uses pickle for multiprocessing stuff, and then something else for when we want to write to disk.  I'm not sure what the best way to do this is.  Maybe add a `PhasePSF.write()` method?

**Comment by jmeyers314** [comment] 2019-11-01 17:26
Maybe add a `write` method, and an optional `screen_file` kwarg to the constructor.  Then when unpickling, first check the global dict, and fall back to reading `screen_file` if that fails...?  I'll play with this today.

**Comment by jmeyers314** [comment] 2019-11-01 19:57
Added `readScreenShare` and `writeScreenShare` to the GalSim `atm_pkl` branch which just load and unload the shared memory directly.  If that looks okay, then I'll make an ImSim PR this afternoon.

**Comment by rmjarvis** [comment] 2019-11-01 20:16
LGTM.  You should make a PR to make it official, but I've basically already code reviewed it.  Then we can make a v2.2.2 with this fix.

**Comment by cwwalter** [comment] 2021-01-21 18:41
I think this was fixed, is that correct @jmeyers314 and @rmjarvis ?

**Comment by rmjarvis** [comment] 2021-01-21 19:14
Yes.  In GalSim v2.2.2.

**Comment by cwwalter** [comment] 2021-01-21 19:15
Thanks. Closing.

**Closed by cwwalter** 2021-01-21 19:15 UTC
Labels: bug
