### ISSUE TITLE
CatSim and PhoSim disagree on counts

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/imSim#78] opened 2017-11-13 22:00 UTC
During the course of getting the proto DC2 catalog ready to interface with CatSim and PhoSim, I noticed that CatSim predicts a different number of photons for a given SED at a given normalization than PhoSim simulates.  The difference seems to be a pretty constant factor of 0.8 (CatSim predicts fewer photons than PhoSim simulates).  This could be as simple as differing versions of the throughput curves.  It could be more complicated, as well.  I am creating this issue to keep track of our attempts to explain what is going on.

This is relevant to ImSim because ImSim uses CatSim's ADU predictions to set the fluxes of objects that it passes to GalSim.

**Comment by fjaviersanchez** [comment] 2017-11-13 22:38
Does PhoSim include the throughput of the 3rd mirror? I found that it was missing in earlier iterations of the lsst throughputs repo

**Comment by danielsf** [comment] 2017-11-13 23:05
PhoSim includes its own, independent implementation of all of the optical throughputs, so if the throughputs repo did fail to include m3, then that would be a difference between the two.  Looking at the m3 throughput file here

https://github.com/lsst/throughputs/blob/master/baseline/m3.dat

That would be factor of between 0.86 to 0.9, rather than a factor of 0.9.

I will check that `total_*.dat` includes the `m3.dat` throughput in the throughput repository.

**Comment by cwwalter** [comment] 2018-04-12 02:01
@danielsf was this ever resolved? Or should we leave this open?

**Comment by fjaviersanchez** [comment] 2018-04-12 17:05
@cwwalter I was actually checking some exposures with DESCQA here: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-12_2 and they don't agree but I think it's because of vignetting (in this particular visit the central rafts hadn't been simulated yet). I checked others and they looked like they actually agreed. I can run some more to convince us.

**Comment by cwwalter** [comment] 2018-04-13 02:50
It's strange, I got an email from @fjaviersanchez with a new comment but don't see it here now.. anyway:

OK; you say "This is relevant to ImSim because ImSim uses CatSim's ADU predictions to set the fluxes of objects that it passes to GalSim." so if we believe CatSim then imSim will give us the "correct" number but there will be a problem with PhoSim. Alternatively, it means there is a catSim problem correct?  

Do we have a way to distinguish?  The reason I re-pinged people on the issue was I wanted to make sure there was no PhoSim issue we should let people know about in the DC2 repo right away.

**Comment by cwwalter** [comment] 2018-04-13 03:55
@fjaviersanchez Can you easily check again if PhoSim now includes the issue you found before when you and David did your tests?

> Does PhoSim include the throughput of the 3rd mirror? I found that it was missing in earlier iterations of the lsst throughputs repo

**Comment by cwwalter** [comment] 2018-04-13 03:56
Oh actually your comment was that it was missing in the throughput directory.  But Scott checked that already.  Sorry.

**Comment by danielsf** [comment] 2018-04-13 17:39
I actually hadn't gotten around to checking before, but I just did and: yes, the `total_*.dat` and `hardware_*.dat` files in the `throughputs` package do include all of the components they are supposed to.

It's possible that I wasn't careful about making sure I was comparing PhoSim and CatSim at the same airmass values.  I will put together a more rigorous test and report back here.

**Comment by danielsf** [comment] 2018-04-13 21:07
Okay.  I think this is a discrepancy between PhoSim and CatSim.

I used PhoSim to simulate 16 sources with a flat SED on the R22S11 chip.  This simulation was run in `opticsonlymode`, which means that there is no atmosphere and no throughput due to the detector.  I then compared the `gain*ADU` value predicted by CatSim with the median of the reported number of photons in the centroid file.  The ratio of CatSimValue/PhoSimValue is, for each filter:

u: 0.811
g: 0.915
r: 0.897
i: 0.865
z: 0.859
y: 0.472  (more on this later)

Just doing the most naive thing imaginable and replacing the CatSim `throughputs/baseline/filter_*.dat` data with the data in `$PHOSIM_DIR/data/lsst/filter_*.txt' (taking an angle of incidence=19 degrees), I get ratios of CatSimValue/PhoSimValue

u: 0.873
g: 0.973
r: 0.959
i: 0.944
z: 0.930
y: 0.544

PhoSim also has its own files specifying throughput for the lenses and mirrors.  If I were being careful, I would try swapping those in as well to see if the ratios go to 1.  Regardless: there is obviously a discrepancy between the throughputs being used by PhoSim and those being used by CatSim.

What's up with the y filter?

If you look at `$PHOSIM_DIR/data/lsst/filters_5.txt`, the y-band as non-zero (in fact, almost unity) throughput all the way out to lamda=1.2 microns.  In CatSim, the y-band throughput goes to zero at 1.1 microns.  Furthermore, I do not know what PhoSim does about the fact that the y-band throughput is unity at the end of the wavelength grid.  The SED I simulated has flux out to 2 microns.  Maybe PhoSim extrapolates the throughput, which is why CatSim and PhoSim still disagree by a factor of 2, even when I use the PhoSim throughput for y-band.

It seems like people with authority should discuss where the various throughput files are coming from and which is correct.

I am using PhoSim version 3.7.9 and the version of the `throughputs` repository tagged 2017.01.31

**Comment by cwwalter** [comment] 2018-04-13 21:13
Thanks Scott!

I think we should do the following (since it seems this is not really an imSim issue).

Can you open a new issue with your text above tagging John in the DC2 repo?  Then we can discuss more generally with experts what this means and what the cause may be etc.   I'm not sure where the PhoSim files come from so John may be able to shed light on it.

It's hard to compare because of the angular dependence in the files in PhoSim.  I guess my only question is, if you put in some number different than 19 deg does the change your conclusion?

**Comment by danielsf** [comment] 2018-04-13 21:15
I plotted the transmission column versus the wavelength column from`filter_5.txt` (so: effectively stacking all of the angles of incidence on top of each other).  The resulting curve was not that thick (i.e. there was not a lot of change with respect to angle).

**Comment by cwwalter** [comment] 2018-04-27 03:47
I'm closing this as the discussion has moved issue 150 in the DC2 Repo (https://github.com/LSSTDESC/DC2_Repo/issues/150).

**Closed by cwwalter** 2018-04-27 03:47 UTC
